---
- name: Provision Beelink media server
  hosts: beelink
  become: true
  roles:
    - common
    - storage
    - docker
    - media_stack
    - glance
    - monitoring
    - administration
    - adguard