---
# Base packages installed on the host.
common_packages:
  - sudo
  - curl
  - ca-certificates
  - gnupg
  - git
  - vim
  - htop
  - locales

# System timezone — change if you're not in this zone.
common_timezone: Europe/Paris

# Locale to ensure is generated.
common_locale: en_US.UTF-8
